blueprint:
  name: deCONZ - Philips Hue Dimmer Switch - Custom Actions (v2/RWL022)
  description: Customizable actions for Philips Hue Dimmer Switch buttons.
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      selector:
        device:
          integration: zha
          multiple: false
          model: RWL022

    on_press:
      name: Button 1 (ON) - Short press 
      default: []
      selector:
        action: {}
    on_hold:
      name: Button 1 (ON) - Hold
      default: []
      selector:
        action: {}
    up_press:
      name: Button 2 (UP) - Short press 
      default: []
      selector:
        action: {}
    up_hold:
      name: Button 2 (UP) - Hold
      default: []
      selector:
        action: {}
    down_press:
      name: Button 3 (DOWN) - Short press 
      default: []
      selector:
        action: {}
    down_hold:
      name: Button 3 (DOWN) - Hold 
      default: []
      selector:
        action: {}
    off_press:
      name: Button 4 (OFF/Hue) - Short press
      default: []
      selector:
        action: {}
    off_hold:
      name: Button 4 (OFF/Hue) - Hold 
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input remote

action:
  - variables:
      event: '{{ trigger.event.data.event }}'
  - choose:
    - conditions:
      - '{{ event == 1002 }}'
      sequence: !input on_press
    - conditions:
      - '{{ event == 1001 }}'
      sequence: !input on_hold
    - conditions:
      - '{{ event == 2002 }}'
      sequence: !input up_press
    - conditions:
      - '{{ event == 2001 }}'
      sequence: !input up_hold
    - conditions:
      - '{{ event == 3002 }}'
      sequence: !input down_press
    - conditions:
      - '{{ event == 3001 }}'
      sequence: !input down_hold
    - conditions:
      - '{{ event == 4002 }}'
      sequence: !input off_press
    - conditions:
      - '{{ event == 4001 }}'
      sequence: !input off_hold
