blueprint:
  name: ZHA - Philips Hue Dimmer Switch - Custom Actions with Defaults (v3/RWL022)
  description: >
    Customizable actions for Philips Hue Dimmer Switch buttons with default actions
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      selector:
        device:
          integration: zha
          multiple: false
          model: RWL022

    area_target:
      name: Target Area
      description: "Select the area to control with the dimmer switch."
      selector:
        area: {}

mode: single
max_exceeded: silent

variables:
  device_id: !input "remote"

trigger:
  - platform: event
    event_type: zha_event
condition: "{{ trigger.event.data.device_id == device_id }}"
actions:
  - action: >
      {% if trigger.event.data.command == "on_press" %}
        light.toggle
      {% endif %}
    target: !input "area_target"
