blueprint:
  name: ZHA Dimmer Switch Area Controller
  description: >
    This automation blueprint allows you to control lights in a specified area
    using a ZHA dimmer switch. When the dimmer switch is pressed, it toggles
    the lights in the selected area. You can customize the action to perform
    other services if needed. The automation ensures that only the switch within
    the specified area triggers the action.
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      description: Select the ZHA dimmer switch device to use as a controller.
      selector:
        device:
          integration: zha
          multiple: false
          model: RWL022

    area_target:
      name: Target Area
      description: Select the area to control with the dimmer switch.
      selector:
        area: {}

    action_service:
      name: Action Service
      description: Select the service to call when the dimmer switch is pressed.
      selector:
        action: {}
      default: light.toggle

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

condition:
  - condition: template
    value_template: "{{ device_attr(trigger.event.data.device_id, 'area_id') == area_target }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on_press' }}"
        sequence:
          - service: '{{ action_service }}'
            target:
              area_id: !input area_target
