blueprint:
  name: TEST
  description: TEST
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      selector:
        device:
          integration: zha
          multiple: false
          model: RWL022

    area_target:
      name: Target Area
      description: "Select the area to control with the dimmer switch."
      selector:
        area: {}

    action_service:
      name: Action Service
      description: "Select the service to call when the dimmer switch is pressed."
      selector:
        action: {}
      default: light.toggle

trigger:
  - platform: event
    event_type: zha_event

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on_press' }}"
        sequence:
          - service: '{{ action_service }}'
            target:
              area_id: !input area_target
